# Generated by Django 4.2.4 on 2023-08-26 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '__first__'),
        ('usuario', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('descripcion', models.TextField()),
                ('url_video', models.CharField(max_length=300)),
                ('minutos_video', models.CharField(max_length=20)),
                ('estado', models.IntegerField(default=1, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('portada', models.CharField(max_length=90)),
                ('url_video_intro', models.CharField(max_length=90)),
                ('url_portada_det', models.CharField(max_length=90)),
                ('hora_duracion', models.IntegerField()),
                ('total_clases', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('estado', models.IntegerField(default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sesion', models.CharField(max_length=90)),
                ('descripcion', models.TextField()),
                ('estado', models.IntegerField(default=1, verbose_name='Estado')),
                ('id_curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestorcursos.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('tipo_recurso', models.CharField(max_length=45)),
                ('url', models.CharField(max_length=45)),
                ('archivo', models.CharField(max_length=80)),
                ('estado', models.IntegerField(default=1, verbose_name='Estado')),
                ('id_contenido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestorcursos.contenido')),
            ],
        ),
        migrations.CreateModel(
            name='CursoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestorcursos.curso')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='contenido_vistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_video', models.CharField(max_length=5)),
                ('id_contenido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestorcursos.contenido')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='contenido',
            name='id_sesion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestorcursos.sesion'),
        ),
    ]
