# Generated by Django 3.2.20 on 2023-07-28 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('correcta', models.BooleanField(default=True, verbose_name='Correcta')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('descripcion', models.TextField()),
                ('url_video', models.CharField(max_length=300)),
                ('minutos_video', models.CharField(max_length=20)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('portada', models.CharField(max_length=90)),
                ('url_video_intro', models.CharField(max_length=90)),
                ('url_portada_det', models.CharField(max_length=90)),
                ('hora_duracion', models.IntegerField()),
                ('total_clases', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('puntos', models.IntegerField()),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('id_examen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestorcursos.examen')),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_seccion', models.CharField(max_length=90)),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('id_curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestorcursos.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_alternativa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestorcursos.alternativa')),
                ('id_pregunta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestorcursos.pregunta')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ResolverExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion_total', models.IntegerField()),
                ('calificacion_final', models.IntegerField()),
                ('notas', models.TextField()),
                ('examen_terminado', models.BooleanField(default=True, verbose_name='ExamenTerminado')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('id_examen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestorcursos.examen')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Requisitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisitos', models.TextField()),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('id_curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestorcursos.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('tipo_recurso', models.CharField(max_length=45)),
                ('url', models.CharField(max_length=45)),
                ('archivo', models.CharField(max_length=80)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('id_clase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestorcursos.clase')),
            ],
        ),
        migrations.AddField(
            model_name='examen',
            name='id_seccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestorcursos.seccion'),
        ),
        migrations.CreateModel(
            name='DetalleResolverExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('id_alternativa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestorcursos.alternativa')),
                ('id_pregunta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestorcursos.pregunta')),
                ('id_resolver_examen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestorcursos.resolverexamen')),
            ],
        ),
        migrations.CreateModel(
            name='CursoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestorcursos.curso')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Curso_Temas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temas', models.TextField()),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('id_curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestorcursos.curso')),
            ],
        ),
        migrations.CreateModel(
            name='clases_vistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('tipo_recurso', models.CharField(max_length=5)),
                ('id_clase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestorcursos.clase')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='clase',
            name='id_seccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestorcursos.seccion'),
        ),
        migrations.CreateModel(
            name='CalificacionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta1', models.IntegerField()),
                ('pregunta2', models.IntegerField()),
                ('pregunta3', models.IntegerField()),
                ('pregunta4', models.IntegerField()),
                ('pregunta5', models.IntegerField()),
                ('pregunta6', models.CharField(max_length=150)),
                ('pregunta7', models.IntegerField()),
                ('pregunta8', models.IntegerField()),
                ('pregunta9', models.IntegerField()),
                ('pregunta10', models.IntegerField()),
                ('promedio_calificacion', models.DecimalField(decimal_places=2, max_digits=3)),
                ('id_curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestorcursos.curso')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='alternativa',
            name='id_pregunta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestorcursos.pregunta'),
        ),
    ]
