# Generated by Django 3.2.20 on 2023-07-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=300)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('rol', models.IntegerField()),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=9)),
                ('dni', models.CharField(max_length=7)),
                ('correo', models.CharField(max_length=250)),
                ('direccion', models.CharField(max_length=250)),
                ('foto', models.CharField(max_length=250)),
                ('carrera', models.CharField(max_length=250)),
                ('perfil', models.TextField()),
            ],
        ),
    ]
